# Generated by Django 5.2.3 on 2025-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
