# Generated by Django 5.2.3 on 2025-07-13 09:34

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_productimages_product'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
